<?php

/**
 * @file
 * Contains assessments.module.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_views_data_alter().
 */
function anu_lms_assessments_views_data_alter(array &$data) {
  $data['assessment_question_result']['assessment_result']['relationship'] = [
    'title' => t('Quiz result'),
    'label' => t('Quiz result'),
    'group' => 'Question result',
    'help' => t('Reference to the quiz result for question results'),
    'id' => 'standard',
    'base' => 'assessment_result',
    'base field' => 'aqrid',
    'field' => 'id',
  ];

  $data['assessment_question_result']['assessment_question']['relationship'] = [
    'title' => t('Qestion'),
    'label' => t('Qestion'),
    'group' => 'Question result',
    'help' => t('Reference to the Question asked'),
    'id' => 'standard',
    'base' => 'assessment_question',
    'base field' => 'id',
    'field' => 'aqid__target_id',
  ];
}

/**
 * Workaround to show translatable fields inside nested paragraphs.
 *
 * @param $entity_form
 *   Nested array of form elements that comprise the entity form.
 * @param $form_state
 *   The form state of the parent form.
 */
function anu_lms_assessments_inline_entity_form_entity_form_alter(&$entity_form, &$form_state) {
  $children = Element::children($entity_form);

  foreach ($children as $field_name) {
    if (!empty($entity_form[$field_name]['#multilingual']) && $entity_form[$field_name]['#multilingual']) {
      $entity_form[$field_name]['#access'] = true;
    }
  }
}
