version: 2.1

orbs:
    browser-tools: circleci/browser-tools@1.2.5

jobs:
  build:
    docker:
      - image: cimg/php:8.1-browsers
    environment:
      SIMPLETEST_BASE_URL: http://localhost:8888
      SIMPLETEST_DB: sqlite://localhost/tmp/db.sqlite
      SYMFONY_DEPRECATIONS_HELPER: disabled
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox", "--disable-dev-shm-usage"]}}, "http://localhost:9515"]'
    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Install required packages
          command: |
            sudo add-apt-repository -y ppa:ondrej/php
            sudo apt update && \
            sudo apt install -y php8.0-sqlite3
      - checkout:
          path: anu_lms
      - run:
          name: Install recommended drupal projects
          command: composer create-project drupal/recommended-project:^9 anu_drupal
      - run:
          name: Prepare project with anu_lms in the codebase
          working_directory: anu_drupal
          # TODO: When install dev-dependencies from main composer.json.
          # Moving the project to Drupal.org will remove the need to do this.
          command: |
            composer config repositories.systemseed/anu_lms path ../anu_lms && \
            composer config minimum-stability dev && \
            composer require "systemseed/anu_lms:*@dev" && \
            composer require --dev drupal/core-dev:^9 drupal/pathauto && \
            composer require --dev dealerdirect/phpcodesniffer-composer-installer && \
            composer require --dev phpspec/prophecy-phpunit:^2
      - run:
          name: Run PHP code sniffer
          working_directory: anu_drupal
          command: |
            vendor/bin/phpcs --standard=Drupal --ignore=node_modules,vendor,dist,js web/modules/contrib/anu_lms/
      - run:
          name: Install nodejs dependencies
          working_directory: anu_lms/js
          command: npm install
      - run:
          name: Run eslint
          working_directory: anu_lms/js
          command: npm run lint
      - run:
          name: Build assets
          working_directory: anu_lms/js
          command: npm run build
      - run:
          name: Print git status
          working_directory: anu_lms
          command: git status
      - run:
          name: Fail build if there are uncommitted changes after build
          working_directory: anu_lms/js
          command: git diff-index --quiet HEAD --
      - run:
          name: Run Drupal tests
          working_directory: anu_drupal
          command: php -S localhost:8888 -t web/ & chromedriver --whitelisted-ips & sleep 1 && vendor/bin/phpunit -c web/core/phpunit.xml.dist web/modules/contrib/anu_lms/tests
      - store_artifacts:
          path: anu_lms/js/dist
