<?php

namespace Drupal\anu_lms\Event;

use Symfony\Component\EventDispatcher\Event;
use Drupal\Core\Entity\EntityInterface;

/**
 * Event that is fired when the Lesson service generates data.
 */
class LessonPageDataGeneratedEvent extends Event {

  const EVENT_NAME = 'anu_lms_lesson_page_data_generated';

  /**
   * The page data.
   *
   * @var array
   */
  protected $pageData;

  /**
   * The node used to generate the data.
   *
   * @var \Drupal\Core\Entity\EntityInterface
   */
  protected $node;

  /**
   * Constructs the object.
   *
   * @param array $pageData
   *   The data generated by the service.
   * @param \Drupal\Core\Entity\EntityInterface $node
   *   The node that was used to generate the data.
   */
  public function __construct(array $pageData, EntityInterface $node) {
    $this->pageData = $pageData;
    $this->node = $node;
  }

  /**
   * Get the page data.
   */
  public function getPageData() {
    return $this->pageData;
  }

  /**
   * Set the page data.
   */
  public function setPageData(array $data) {
    $this->pageData = $data;
  }

  /**
   * Get the node.
   */
  public function getNode() {
    return $this->node;
  }

}
