<?php

/**
 * @file
 * Contains permissions.module.
 */

use Drupal\Core\Access\AccessResult;

/**
 *  Implements hook_entity_create_access();
 *
 *  @dev: Note the user's drupal role must have access to the
 *  "create new draft" workflow transition.
 */
function anu_lms_permissions_entity_create_access(\Drupal\Core\Session\AccountInterface $account, array $context, $entity_bundle) {
  $groups = [];
  $grp_membership_service = \Drupal::service('group.membership_loader');
  $grps = $grp_membership_service->loadByUser($account);

  foreach ($grps as $grp) {
    $loaded_group = $grp->getGroup();
    $groups[$loaded_group->id()] = $loaded_group;

    // Check group permission to create this entity and, if so, allow.
    if ($loaded_group->hasPermission('create group_node:' . $entity_bundle . ' entity', $account)) {
      return AccessResult::allowed();
    }
  }

  // By default return neutral.
  return AccessResult::neutral();
}
